databases:
  - name: UTAniki_DB
    databaseName: utaniki_db
    user: UTAniki-1
    region: singapore

services:
  - type: web
    name: UTAniki-1
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: UTAniki_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false